apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80       # Port exposed by the service
    targetPort: 80 # Port the container listens on
  type: NodePort   # Change to LoadBalancer if using a cloud provider
